[package]
name = "chapter_6"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "enums"
path = "src/main.rs"

[[bin]]
name = "message"
path = "src/message.rs"

[[bin]]
name = "null"
path = "src/null.rs"

[[bin]]
name = "coin_example"
path = "src/coin_example.rs"
